### ISSUE TITLE
Change SOMap, SSMap, OSMap method signatures

### ISSUE THREAD

**Issue by csstransky** [rohitppathak/-softdev-2020-ai-part2#10]
Could we change the return signatures for the String portions of the Maps to return Strings?
We could cast, but I'd rather do something like:
```
SSMap* string_map = new SSMap();
String* key = new String("hi");
String* value = new String("there");
string_map->put(key, value);

// This is a little painful
String* new_string = dynamic_cast<String*>(string_map->get(key));

// I'd rather to just be able to do this:
String* better_string = string_map->get(key); // this would throw a compiler error
```

I would argue that if we're specifically using a String map, it should be easy to get Strings from it. 

And, instead of having to check and enforce type ourselves, why not just get the compiler to do it for us?
So we'd change the signatures to something like this for a SSMap:
```
String* put(String* key, String* value);

String* get(String* key);
```
That way we can avoid having to type check, and just get the compiler to throw an error itself saying the type isn't matching.

----------------------------
**NOTE:** The question below is dependent on the answer from above. If we change the method signatures, we don't have to worry about type handling.

Can you add to your documentation on the spec what you want to happen when an Object that isn't a String is passed into SSMap, SOMap, or OSMap?

What would happen here?
```
SSMap* string_map = new SSMap();
Object* key = new Object();
String* value = new String("there");

// Do we throw an error?
// Do we do nothing and put nothing into the map?
string_map->put(key, value);
```
--------------------------

If you give us the go ahead, we can start a pull request where we change the signatures as needed.

**Comment by rohitppathak** [comment]
Because our design relies upon an SOMap and an SSMap extending from a Map and overriding its methods, we can't change the signature of an SOMap and SSMap to a String since a Map returns an Object*. We understand the argument that having the compiler do this for us would be better for the user, but we decided against it since it would mean a lot of code duplication on our/your end. 

For the second question, it should throw an error.

**Comment by csstransky** [comment]
So you're suggesting that we cast every result from a SSMap?

If you're worried about code duplication, there really isn't much:
```
String* put(String* key, String* value) {
    return dynamic_cast<String*>(map_->put(key, value));
}
```
This makes sure that you don't have to cast the result yourself, and because you enforce an SSMap to only put Strings, your Map will only have Strings. Trying to do otherwise will throw a compilation error.

**Comment by csstransky** [comment]
The code I wrote above for put is much, much easier than this:
```
// This shouldn't be virtual, nothing inherits this function from SSMap
virtual Object* put(Object* key, Object* value) {
    String* key = dynamic_cast<String*>(key);
    if (key == nullptr) {
        std::cout << "Key is not a String*\n";   
        exit(1);
    }
    String* value = dynamic_cast<String*>(value);
    if (value == nullptr) {
        std::cout << "Value is not a String*\n";   
        exit(1);
    }
    // And then I'll have to cast this result afterwards outside this function
    return map_->put(key, value);
}
```
I would argue that the current spec will require far more code both inside the map.h file and outside the map.h file, than just having the signature for Strings.

**Comment by rohitppathak** [comment]
Yep what you're saying makes sense. We can accept a pull request if you have one, or let us know which methods you want us to change.

**Comment by csstransky** [comment]
Cool, I'll send a pull request later with some suggestions. If you make changes before I can get to it, that's fine too, but I'll try to get to this before the day's done.

**Comment by kaylindevchand** [comment]
Created pull request #16.

**Comment by rohitppathak** [comment]
Merged, thanks
