### ISSUE TITLE
What to do when no Object is found

### ISSUE THREAD

**Issue by csstransky** [rohitppathak/-softdev-2020-ai-part2#11]
Can you add to your documentation on what would happen if no Object is found for a certain method?

Example:
```
Map* string_map = new Map();
String* key = new String("not there");

// Does it return a nullptr?
// Does it return a new Object?
Object* new_string = string_map->get(key);
```
The functions that are effected by this are:
+ get
+ put
+ remove

**Comment by rohitppathak** [comment]
Return a nullptr. The docs should be updated now.

**Comment by csstransky** [comment]
Perfect, thanks.
