### ISSUE TITLE
Add Constructors to Each Map Class

### ISSUE THREAD

**Issue by csstransky** [rohitppathak/-softdev-2020-ai-part2#12]
Can you add constructors to each of your Map classes?

I'd really love to avoid having to duplicate code from Map into each and every class, and instead have a constructor that would let me do this:
```
class SSMap : public Map {
    public:
        Map* map_;
        SSMap() {
            map_ = new Map();
        }
};
```

**Comment by rohitppathak** [comment]
Why would an SSMap have a map_ if it already is a Map?

**Comment by csstransky** [comment]
Great point, I found a much simpler and more memory efficient way to do this instead like this:
`Map::put(key, value);`
