### ISSUE TITLE
Various test file changes

### ISSUE THREAD

**Issue by canonsawrey** [rohitppathak/-softdev-2020-ai-part2#13]
While running our tests, we found a few issues with the test file. 
 - Move main method to bottom of test file
 - Add parens () to the end of size (lines 40, 42, 46, 50)

**Comment by rohitppathak** [comment]
Fixed

**Comment by canonsawrey** [comment]
A few more things:
 - Removal of `aKey` multiple times (Lines 39 and 41 and other related lines in other tests)
 - For `putAll`, objects are not added to `map2`

**Comment by rohitppathak** [comment]
I fixed the aKey issue. I don't understand the second issue, can you point me to line number?

**Comment by canonsawrey** [comment]
47-52

**Comment by canonsawrey** [comment]
Initializes objects to be put into map2, but never actually `puts` them

**Comment by rohitppathak** [comment]
Gotchu, fixed

**Comment by canonsawrey** [comment]
Could you also add parens to size one lines 98, 100, 104, 108 please

**Comment by rohitppathak** [comment]
Sure fixed. You can also make a pull request with your changes as well which is probably easier for both of us

**Comment by canonsawrey** [comment]
Will do. Thanks for making those
