### ISSUE TITLE
Incorrect test case

### ISSUE THREAD

**Issue by xeniarose** [rohitppathak/-softdev-2020-ai-part2#17]
In both testBasicSOMap and testBasicSSMap the assertions `t_true(values->index_of(a) < values->size())` are not correct because the maps at those points do not contain `a` as a value anymore because of the update performed by `map->put(aKey, newA)`

The correct assertion would be ` t_true(values->index_of(newA) < values->size())`

**Comment by rohitppathak** [comment]
Fixed
