### ISSUE TITLE
Remove list.h and change return to Array

### ISSUE THREAD

**Issue by Coderrine** [rohitppathak/-softdev-2020-ai-part2#3]
Given that we are all implementing Arrays, could you please change the return values of List to Array (in the "keySet()" and "values()" methods) and fix the tests accordingly? Also please remove list.h as it is unnecessary.

**Comment by rohitppathak** [comment]
Just updated `map.h` and README. I also deleted the list.h file. Note you now need an `array.h` file to compile the `map.h` file.

**Comment by rohitppathak** [comment]
I also fixed the test file to use arrays. Because it depends on each individual group's Array implementation (specifically the naming of the index_of method), make sure to either change your implementation or the tests.
