### ISSUE TITLE
Question: when methods are storing/returning objects are they making copies?

### ISSUE THREAD

**Issue by Coderrine** [rohitppathak/-softdev-2020-ai-part2#4]
Since we are storing pointers to Objects, it is important to understand whether these are pointers to the original (corresponding to the keys or values) or whether they are pointers to newly allocated copies. This changes the way the methods are written and changes the API of object.h. Please revise comments as appropriate. Thank you!

**Comment by kyleacmooney** [comment]
Just commenting to let the owners of this repo know that we learned Vitek's recommendation is to not store or return copies
