### ISSUE TITLE
Map Constructor

### ISSUE THREAD

**Issue by csstransky** [rohitppathak/-softdev-2020-ai-part2#6]
Can there be constructors for at least the Map class?

I'd like to initialize values like "size", and I'd prefer it over decorator methods (which don't seem present either).

Also, for my future issues, if you give me the go-ahead here, I'll make pull requests so you only have to approve them instead of having to write the code yourself.

**Comment by rohitppathak** [comment]
Sure. And yeah pull requests are good.

**Comment by csstransky** [comment]
Made the pull request. I'll add more constructors to the other classes if I need to for whatever reason.

Edit: #7 <- pull request here

**Comment by rohitppathak** [comment]
Just merged
