### ISSUE TITLE
Object.h, equals argument should not be const

### ISSUE THREAD

**Issue by Coderrine** [rohitppathak/-softdev-2020-ai-part2#9]
virtual bool equals(Object* const obj) -> virtual bool equals(Object* obj);

**Comment by rohitppathak** [comment]
This is the default String class that Piazza post @345 references. I don't want to change it since it isn't created by me. Maybe make an issue on the author's repo?

**Comment by Coderrine** [comment]
All good! We were confused because that repo's readme does not match their code.
